server:
  port: 8080
  error:
    include-stacktrace: always
spring:
  datasource:
    driverClassName: ${SPRING_DATASOURCE_DRIVER-CLASS-NAME}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL-AUTO}
    connection:
      characterEncoding: utf-8
      CharSet: utf-8
      useUnicode: true
